name: Bug Report
description: Submit a bug report
title: "[Bug]: "
labels: "Bug"
body:
  - type: input
    id: version
    attributes:
      label: What version of SimpleDatatexts are you using?
      placeholder: e.g. 12.0.0.01
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: What is the issue?
      description: Please include a detailed description of what issue occurred, as well as any lua errors that accompany the issue. You may also include a screenshot, if you wish.
    validations:
      required: true